# Header
menu:
  Home: /
  Tags: /tags
  Categories: /categories
  Github: https://github.com/distantcam || github
  Feed: /feed.rss || feed

social:
  twitter: https://twitter.com/distantcam
  github: https://github.com/distantcam
  instagram: https://www.instagram.com/distantcam
  stack-overflow: https://stackoverflow.com/users/3820

images:
  default:
  show_thumbnails: false

unsplash:
  default_id: aOC7TSLb1o8
  default_user: Lauren Mancke
  header: 1600x1200

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# Title for untitled posts. Defaults to '(no title)'
default_post_title: 

# To get or check favicons visit: https://realfavicongenerator.net
# Put your favicons into `hexo-site/source/` directory.
favicon:
  # apple_touch_icon: /apple-touch-icon.png
  # medium: /favicon-32x32.png
  # small: /favicon-16x16.png
  # site_webmanifest: /site.webmanifest
  # safari_pinned_tab: /safari-pinned-tab.svg
  # safari_color: "#5bbad5"
  # tilecolor: "#da532c"
  # theme_color: "#ffffff"

google_analytics:

feed:
  title: Subscribe to What's New
  url: /feed.rss
  type: rss

comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light
  # Gitment comments
  gitment:
    github_owner: # MUST HAVE, Github owner of repo
    github_admin: # Admin of repo, if owner is not the user
    github_repo:  # MUST HAVE, The name of the repo you use to store Gitment comments
    client_id:    # MUST HAVE, Github client id for the Gitment
    client_secret: # EITHER this or proxy_gateway, Github access secret token for the Gitment
    proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
    language: # Force language, or auto switch by theme
